spring.application.name=eamil-writer

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
gemini.api.key=AIzaSyC9FYkP7xe360kpCG3LNFi07vs2bSXI2Kw


